name: openbook_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  google_sign_in: ^6.3.0
  shared_preferences: ^2.3.2
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  cloud_firestore: ^6.0.0
  intl: ^0.19.0
  firebase_storage: ^13.0.0
  qr_flutter: ^4.1.0
  file_picker: ^10.2.4
  url_launcher: ^6.3.0
  http: ^1.5.0
  flutter_colorpicker: ^1.0.3
  emoji_picker_flutter: ^1.0.4 # For emoji picker
  # giphy_picker: ^0.2.2 # For Giphy sticker picker
  intl_phone_field: ^2.1.0 # You can use this package to allow selecting country code



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  characters: ^1.4.1
  leak_tracker: ^11.0.1
  leak_tracker_flutter_testing: ^3.0.10
  leak_tracker_testing: ^3.0.2
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  petitparser: ^7.0.0
  test_api: ^0.7.7
  vector_math: ^2.2.0
  vm_service: ^15.0.2
  xml: ^6.6.0
  _flutterfire_internals: ^1.3.60
  cloud_firestore_platform_interface: ^7.0.0
  cloud_firestore_web: ^5.0.0
  firebase_auth_platform_interface: ^8.0.0
  firebase_auth_web: ^6.0.0
  firebase_core_web: ^3.0.0
  firebase_storage_platform_interface: ^5.2.11
  firebase_storage_web: ^3.10.18

flutter:
  uses-material-design: true
  assets:
    - assets/images/openbook_logo_icon.png
    - assets/logos/google_logo.svg
    - assets/logos/apple_logo.svg
    - assets/logos/facebook_logo.svg
    - assets/images/avatars/zah_avatar.png
    - assets/images/avatars/sumitra_avatar.png
    - assets/images/avatars/liam_avatar.png
    - assets/images/avatars/default_avatar.png
