// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgoH1zHMKHNAdFsAQAOKkvmMidTwN_b8w',
    appId: '1:735348547978:web:c9cb241214bb2f67f6a873',
    messagingSenderId: '735348547978',
    projectId: 'open-book-16zt1k',
    authDomain: 'open-book-16zt1k.firebaseapp.com',
    storageBucket: 'open-book-16zt1k.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtOXOHJ4m-b7T6NA93re9qCoe2daCAZhs',
    appId: '1:735348547978:android:13ba181ffe97ff51f6a873',
    messagingSenderId: '735348547978',
    projectId: 'open-book-16zt1k',
    storageBucket: 'open-book-16zt1k.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfEQEp82Te6jTcbL1OgTy8lQ9ODIk_t8g',
    appId: '1:735348547978:ios:cbcc1d76e82d775df6a873',
    messagingSenderId: '735348547978',
    projectId: 'open-book-16zt1k',
    storageBucket: 'open-book-16zt1k.firebasestorage.app',
    iosClientId: '735348547978-n2t49kp1hpmd84tqjq2gke1rp6vpr8us.apps.googleusercontent.com',
    iosBundleId: 'com.example.openbookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfEQEp82Te6jTcbL1OgTy8lQ9ODIk_t8g',
    appId: '1:735348547978:ios:cbcc1d76e82d775df6a873',
    messagingSenderId: '735348547978',
    projectId: 'open-book-16zt1k',
    storageBucket: 'open-book-16zt1k.firebasestorage.app',
    iosClientId: '735348547978-n2t49kp1hpmd84tqjq2gke1rp6vpr8us.apps.googleusercontent.com',
    iosBundleId: 'com.example.openbookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgoH1zHMKHNAdFsAQAOKkvmMidTwN_b8w',
    appId: '1:735348547978:web:8c59f35acabc5df3f6a873',
    messagingSenderId: '735348547978',
    projectId: 'open-book-16zt1k',
    authDomain: 'open-book-16zt1k.firebaseapp.com',
    storageBucket: 'open-book-16zt1k.firebasestorage.app',
  );
}