import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:openbook_app/home_screen.dart';
import 'package:openbook_app/login_page.dart'; // 👈 import your login page
import 'firebase_options.dart'; // generated by FlutterFire CLI

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // 👇 Change this to true to show login, false to auto-login
  static const bool showLogin = true;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'OpenBook',

      // Force dark theme
      themeMode: ThemeMode.dark,

      // Light theme
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.blue,
          brightness: Brightness.light,
        ),
      ),

      // Dark theme with blue accent
      darkTheme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.blue,
          brightness: Brightness.dark,
        ),
        scaffoldBackgroundColor: Colors.black,
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.black,
          foregroundColor: Colors.white,
        ),
        bottomNavigationBarTheme: const BottomNavigationBarThemeData(
          backgroundColor: Colors.black,
          selectedItemColor: Colors.blue,
          unselectedItemColor: Colors.grey,
        ),
        chipTheme: const ChipThemeData(
          labelStyle: TextStyle(color: Colors.white),
          brightness: Brightness.dark,
        ),
      ),

      // 👇 Toggle between login page and home screen
      home: showLogin ? const LoginPage() : const HomeScreen(),
    );
  }
}
