# ios/Podfile
platform :ios, '13.0'
use_frameworks! :linkage => :static
use_modular_headers!

require File.expand_path(File.join('..', 'Flutter', 'podhelper.rb'), __FILE__)
flutter_ios_podfile_setup

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
